# Generated by Django 2.0.7 on 2018-07-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='is_additional',
            field=models.BooleanField(verbose_name='Indicates if an item is additional'),
        ),
    ]
