# Generated by Django 2.0.7 on 2018-07-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliation',
            name='company',
        ),
    ]
