# Generated by Django 2.0.7 on 2018-07-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_avaliation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliation',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
