# Generated by Django 2.0.7 on 2018-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180719_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status of the attribute'),
        ),
        migrations.AlterField(
            model_name='orderattribute',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Indicates whether the attribute was removed and added to this order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status of the product'),
        ),
    ]
