# Generated by Django 2.0.7 on 2018-07-25 22:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180725_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Attribute.attribute_directory_path),
        ),
    ]
