# Generated by Django 2.0.7 on 2018-08-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180817_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Table available'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
    ]
