# Generated by Django 2.0.7 on 2018-08-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180817_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=45, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=45, verbose_name='Phone'),
        ),
    ]
