# Generated by Django 2.0.7 on 2018-08-23 01:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180818_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Category.category_directory_path, verbose_name='Image of the Category'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Company.company_directory_path, verbose_name='Log of Company'),
        ),
    ]
