# Generated by Django 2.0.7 on 2018-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180823_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
