# Generated by Django 2.0.7 on 2018-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180825_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50, null=True, verbose_name='Color of the company'),
        ),
    ]
