# Generated by Django 2.0.7 on 2018-08-25 19:54

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_company_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ingredient Name')),
                ('is_additonal', models.BooleanField(default=True, verbose_name='Can is additional?')),
                ('status', models.BooleanField(default=True, verbose_name='Status: available?')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.Ingredient.ingredient_directory_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_selected', models.BooleanField(default=True, verbose_name='Indicates whether the ingredient was removed and added to this order')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(default=0.0, verbose_name='Quantity grams of the produtc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingredient')),
                ('prodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='orderattribute',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='OrderAttribute',
        ),
        migrations.AddField(
            model_name='ingredientorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredient',
            field=models.ManyToManyField(through='api.IngredientOrder', to='api.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(through='api.ProductIngredient', to='api.Ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('company', 'name')},
        ),
    ]
