# Generated by Django 2.0.7 on 2018-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180825_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attribute',
            field=models.ManyToManyField(to='api.Attribute'),
        ),
    ]
