# Generated by Django 2.0.7 on 2018-08-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='is_additonal',
            new_name='is_additional',
        ),
        migrations.AlterField(
            model_name='ingredientorder',
            name='is_selected',
            field=models.BooleanField(default=True, verbose_name='Is selected?'),
        ),
    ]
