# Generated by Django 2.0.7 on 2018-08-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180825_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productingredient',
            old_name='prodcut',
            new_name='product',
        ),
    ]
