# Generated by Django 2.0.7 on 2018-08-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180825_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Barbalha', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='CE', max_length=5, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(default='company default', max_length=45, unique=True, verbose_name='Fantasy name'),
        ),
    ]
